# Generated by Django 3.1.14 on 2024-01-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter_Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3, verbose_name='زبان کاربر')),
                ('email', models.CharField(max_length=40, verbose_name='رایانامه')),
                ('join_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'اعضای خبرنامه',
            },
        ),
    ]
